name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest # You can specify windows-latest or macos-latest if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          # This will read the .NET version from your global.json file
          # If you don't have one, specify the version directly
          # dotnet-version: '8.0.x'
          global-json-file: global.json

      - name: Setup Taskfile
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env file
        run: |
          # The public.env should be committed to your repository
          cp public.env .env
          # For pull requests, we don't need a real NuGet API key.
          # If other secrets were needed for the build/test process,
          # they would be added here from GitHub secrets.
          echo "NUGET_API_KEY=DUMMY_KEY" >> .env
        shell: bash

      - name: Restore .NET local tools
        run: task setup

      - name: Clean the solution
        run: task clean

      - name: Build the solution
        run: task build

      - name: Run tests
        run: task test